### ISSUE TITLE
use with NextJS

### ISSUE THREAD

**Issue by jerearaujo03** [diegoulloao/yup-es#2]
`SyntaxError: Cannot use import statement outside a module` when using with NextJS

**Comment by diegoulloao** [comment]
Yeah, it's a mistake I did.

I'll be fixing it soon. It's urgent for you?

**Comment by jerearaujo03** [comment]
Yap, what would be the solution? I can do a patch meanwhile

**Comment by diegoulloao** [comment]
try the new version I just released: `yup-es@1.0.4`
LMK if works fine to you

**Comment by diegoulloao** [comment]
thanks! try the last version released: https://www.npmjs.com/package/yup-es/v/1.0.7

LMK if it's working fine for you. I also added types definitions so you can import the module with the `import` statement.

**Comment by diegoulloao** [comment]
https://github.com/diegoulloao/yup-es/releases/tag/v1.0.7

**Comment by diegoulloao** [comment]
@jerearaujo03 it's all okay? so we can proceed closing this issue

**Comment by diegoulloao** [comment]
fixed in latest version: https://github.com/diegoulloao/yup-es/releases/tag/v1.0.7

**Comment by jerearaujo03** [comment]
It's working but throwing this error sometimes:

```
Unhandled Runtime Error
TypeError: printValue is not a function

Call Stack
notType
node_modules/yup-es/src/lib/es.js (15:36)
ValidationError.formatError
node_modules/yup/es/ValidationError.js (13:0)
```

**Comment by jerearaujo03** [comment]
It's caused by using `yup.date()`

**Comment by jerearaujo03** [comment]
I was transforming a date with `luxon`, but the value was undefined, resulting in an `Invalid DateTime` value.
In this case, the validation throws an error.

**Comment by diegoulloao** [comment]
Ok, I'll check it out. Let's continue this in another issue.

**Comment by diegoulloao** [comment]
Derived to https://github.com/diegoulloao/yup-es/issues/4
