### ISSUE TITLE
printValue is not a function

### ISSUE THREAD

**Issue by diegoulloao** [diegoulloao/yup-es#4]
It's working but throwing this error sometimes:

```
Unhandled Runtime Error
TypeError: printValue is not a function

Call Stack
notType
node_modules/yup-es/src/lib/es.js (15:36)
ValidationError.formatError
node_modules/yup/es/ValidationError.js (13:0)
```

_Originally posted by @jerearaujo03 in https://github.com/diegoulloao/yup-es/issues/2#issuecomment-1161021370_

**Comment by diegoulloao** [comment]
Context: https://github.com/diegoulloao/yup-es/issues/2#issuecomment-1161046629

**Comment by diegoulloao** [comment]
@jerearaujo03 can you provide a portion of code or steps in order to reproduce the issue?

**Comment by diegoulloao** [comment]
@jerearaujo03 can you try this version? https://www.npmjs.com/package/yup-es/v/1.0.8-beta.1

**Comment by jerearaujo03** [comment]
Same error here :(

**Comment by diegoulloao** [comment]
can you provide some code or something in order I can reproduce the exact issue?

**Comment by jerearaujo03** [comment]
It always happens when this message should be printed:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/7424471/175189081-1a863299-7354-41f7-ab1c-b869a81f797e.png">

In english is working fine, but doesn't with spanish

My schema:
```
export const createPropertySchema = yup
  .object({
    title: yup.string().required().label("Título"),
    description: yup.string().required().label("Descripción"),
    address: yup.string().required().label("Dirección"),
    price: yup.string().required().label("Precio"),
    stateId: yup.string().required().label("Departamento"),
    propertyTypeId: yup.string().required().label("Tipo de propiedad"),
    operationTypeId: yup.string().required().label("Operación"),
    currencyId: yup.string().required().label("Moneda"),
  })
  .required();
```

**Comment by diegoulloao** [comment]
Please try beta 2: https://www.npmjs.com/package/yup-es/v/1.0.8-beta.2

**Comment by jerearaujo03** [comment]
Now is working 🔥
<img width="752" alt="image" src="https://user-images.githubusercontent.com/7424471/175324672-898b73d4-e30a-43ca-a0b1-444344932af4.png">

I would suggest changing the message to:
```
`${path} debe ser de tipo \`${type}\`, ` +
      `pero el valor final fue: \`${printValue(value, true)}\`` +
      (isCast ? ` (Reparto del valor \`${printValue(originalValue, true)}\`).` : ".")
```

**Comment by diegoulloao** [comment]
Ok, changed!

Version `1.0.8` is out: https://www.npmjs.com/package/yup-es/v/1.0.8

Sorry for the bugs.

**Comment by jerearaujo03** [comment]
Nothing to forgive. Awesome work 🚀
