### ISSUE TITLE
Not working with yup 1.0.0

### ISSUE THREAD

**Issue by jerearaujo03** [diegoulloao/yup-es#7]
Was working with yup 0.32.11, but now doesn't work with 1.0.0

It's caused by printValue function, that is not exported anymore

**Comment by diegoulloao** [comment]
Hey @jerearaujo03, thanks for report the issue. I'll check it as soon as possible!

**Comment by diegoulloao** [comment]
Hey, checking yup changes, I can actually see that the function is still being exported from the file.
https://github.com/jquense/yup/blob/33909e7d240c0b19faf619dbd4fa8dd61859c092/src/util/printValue.ts#L36

I'll check locally.

**Comment by Kevinrp22** [comment]
Is there anything new about this? 

I want to update yup to its latest version but I can not because of the error above 🙃

**Comment by diegoulloao** [comment]
@Kevinrp22 hey, sorry, I haven't had time for check this, very tied up in my work...

Anyone interested in debug this?

**Comment by dilanluna** [comment]
It looks like yup don't export _printValue_ function in final bundle

**Comment by diegoulloao** [comment]
It is, I'm thinking in require to the yup creator to export this function again somehow.

**Comment by diegoulloao** [comment]
Please follow this discussion here: https://github.com/jquense/yup/issues/2002

**Comment by diegoulloao** [comment]
Seems like fixed in yup `1.2.0`.
Please check and confirm that's working: https://github.com/jquense/yup/releases/tag/v1.2.0

**Comment by diegoulloao** [comment]
@jerearaujo03 please confirm in order to close this issue

**Comment by dilanluna** [comment]
It doesn't work!

**Comment by diegoulloao** [comment]
PR approved @dilanluna
